### PR TITLE
feat:add form data to localstorage when remember me

### PR DESCRIPTION
**Pull request by sahith29s**
All Submissions:

* [ yes] Have you followed the guidelines in our Contributing document?
* [ yes] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### CODE REVIEW

**Review by musiur — COMMENTED** [review]
You have done! 🎉
- State management for Remember me.
- You have set Credentials in localStorage

### I would suggest to do further!
Let's assume, we have previously logged in and now we are logged out. For the second time we want to login. So, in this scenario we need to give input. But as we have checked remember me at first login. Hence, we expect that our credentials are available in localStorage. We are not going to input rather just want to see that our credentials are automatically added to the form. We need to just click on login.

To be precise:
- When people land on login page get the localStorage credentials if there is any! Here you may need to use useEffect
- Then set that into formData using setFormData
- And also update the remember state as true if localStorage has any credential

I hope, our requirement is clear now!

😅 

For you convenience, 
- You will need to make changes in your repo
- This pull request will be automatically updated
- You may add comment by mentioning me
- Make git pull before starting you changes
- Resolve conflicts
- Then push the changes

Stay blessed!

---

**Comment by sahith29s** [comment]
Bro I am unable to tick the button by default , I tried many different ways .

**Comment by musiur** [comment]
Ok...no issue!

**Review by musiur — APPROVED** [review]

**Comment by sahith29s** [comment]
Honestly thank you for giving me this opportunity this is my first merged pull request, once again thank you bro.

**Pull request merged**
